services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./data:/app/data
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=file:./data/muddakir.db
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  node_modules: